language: swift
osx_image: xcode11
xcode_sdk: iphonesimulator13.0
branches:
  only:
    - master
env:
  - PLATFORM="ios" SCHEME="AlamofireSwiftyJSON" DESTINATION="platform=iOS Simulator,name=iPhone 8,OS=13.0"
script:
  - set -o pipefail && xcodebuild -project Alamofire-SwiftyJSON.xcodeproj -scheme $SCHEME -destination "$DESTINATION" build-for-testing test | xcpretty
