language: objective-c
osx_image: xcode10
xcode_sdk: iphonesimulator12.0
script:
- set -o pipefail
- travis_retry xcodebuild -project Alamofire-SwiftyJSON.xcodeproj -scheme "AlamofireSwiftyJSON" -destination "platform=iOS Simulator,name=iPhone 6" build-for-testing test | xcpretty
