name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: pod install
    - name: Run iOS tests
      run: xcodebuild test -workspace Alamofire-SwiftyJSON.xcworkspace -scheme AlamofireSwiftyJSON -destination platform="iOS Simulator,name=iPhone 11 Pro"
